// This file is generated by Roam. Do not edit it manually.
// Roam - Pi on the Map: roam-pi-on-the-map
// This extension sends only empty local activity heartbeats to Roam.
// It never reads or forwards prompts, messages, tool data, files, or session contents.
import { request } from "node:http";
import { readdir, readFile } from "node:fs/promises";
import { join } from "node:path";

const ENDPOINTS_DIR = "/Users/rohi/.pi/agent/extensions/roam-pi-on-the-map/endpoints";
const REQUEST_TIMEOUT_MS = 200;
const HEARTBEAT_MS = 60000;
const PID = String(process.pid);
let heartbeat;

const isEndpoint = (endpoint) => {
  if (endpoint === null || typeof endpoint !== "object") return false;
  if (typeof endpoint.activePath !== "string" || typeof endpoint.stopPath !== "string") return false;
  const transport = endpoint.transport;
  if (transport === null || typeof transport !== "object") return false;
  if (transport.kind === "unix") return typeof transport.socketPath === "string";
  if (transport.kind === "tcp") return typeof transport.portPath === "string";
  return false;
};

const readEndpoints = async () => {
  try {
    const names = await readdir(ENDPOINTS_DIR);
    const endpoints = [];
    for (const name of names) {
      if (!name.endsWith(".json")) continue;
      try {
        const raw = await readFile(join(ENDPOINTS_DIR, name), "utf8");
        const endpoint = JSON.parse(raw);
        if (isEndpoint(endpoint)) endpoints.push(endpoint);
      } catch {
        // Ignore malformed or unreadable endpoint registrations.
      }
    }
    return endpoints;
  } catch {
    return [];
  }
};

const postWithOptions = (options) => {
  return new Promise((resolve) => {
    let settled = false;
    const done = () => {
      if (settled) return;
      settled = true;
      resolve();
    };
    const req = request(Object.assign({}, options, { timeout: REQUEST_TIMEOUT_MS }), (res) => {
      res.resume();
      res.on("end", done);
    });
    req.on("error", done);
    req.on("timeout", () => {
      req.destroy();
      done();
    });
    req.end();
  });
};

const postToEndpoint = async (endpoint, urlPath) => {
  try {
    const path = urlPath + "?pid=" + encodeURIComponent(PID);
    if (endpoint.transport.kind === "tcp") {
      const rawPort = (await readFile(endpoint.transport.portPath, "utf8")).trim();
      const port = Number(rawPort);
      if (!Number.isInteger(port) || port <= 0) return;
      await postWithOptions({ host: "127.0.0.1", port, path, method: "POST" });
      return;
    }
    await postWithOptions({ socketPath: endpoint.transport.socketPath, path, method: "POST" });
  } catch {
    // Roam may not be running. Pi should continue normally.
  }
};

const post = async (kind) => {
  const endpoints = await readEndpoints();
  await Promise.all(
    endpoints.map((endpoint) => postToEndpoint(endpoint, kind === "stop" ? endpoint.stopPath : endpoint.activePath))
  );
};

export default function (pi) {
  const startHeartbeat = () => {
    if (heartbeat === undefined) {
      heartbeat = setInterval(() => void post("active"), HEARTBEAT_MS);
      heartbeat.unref?.();
    }
    void post("active");
  };

  const stopHeartbeat = async () => {
    if (heartbeat !== undefined) {
      clearInterval(heartbeat);
      heartbeat = undefined;
    }
    await post("stop");
  };

  pi.on("agent_start", startHeartbeat);
  pi.on("agent_end", stopHeartbeat);
  pi.on("session_shutdown", stopHeartbeat);
}